name: BootCamp01

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node JS
      uses: actions/node@v2-beta
      with: 
        node-version: 12
    - name: Install Surge
      run: npm install -g surge
    - name: Run Surge
      run: surge ./ bootcamp_newApp.surge.sh --token ${{secret.SURGE_TOKEN}}
    
      
